spring.application.name=product-service
spring.datasource.url=${POSTGRES_SQL}
spring.datasource.username=${POSTGRES_SQL_USERNAME}
spring.datasource.password=${POSTGRES_SQL_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret-key=${JWT_SECRET_KEY}
springdoc.api-docs.path=/custom-api-docs
springdoc.swagger-ui.path=/custom-swagger-ui
resilience4j.circuitbreaker.instances.productService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.productService.sliding-window-size=10
resilience4j.circuitbreaker.instances.productService.wait-duration-in-open-state=10s
#resilience4j.circuitbreaker.instances.productService.limitForPeriod=5
#resilience4j.circuitbreaker.instances.productService.limitRefreshPeriod=5s
#resilience4j.circuitbreaker.instances.productService.timeoutDuration=5s